//! Alias management module for uwu.
//!
//! Manages PowerShell aliases stored in ~/.uwu/aliases.json.
//! Aliases are loaded into PowerShell sessions via profile integration.

use anyhow::{bail, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use crate::{color, utils};

/// Get the aliases.json file path (~/.uwu/aliases.json)
fn aliases_file() -> PathBuf {
    let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".uwu").join("aliases.json")
}

/// Ensure ~/.uwu directory and aliases.json exist
fn ensure_aliases_file() -> Result<PathBuf> {
    let path = aliases_file();
    if let Some(parent) = path.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent)?;
        }
    }
    if !path.exists() {
        fs::write(&path, "{}")?;
    }
    Ok(path)
}

/// Load aliases from disk
fn load_aliases() -> Result<BTreeMap<String, String>> {
    let path = ensure_aliases_file()?;
    let content = fs::read_to_string(&path)?;
    let aliases: BTreeMap<String, String> = serde_json::from_str(&content)?;
    Ok(aliases)
}

/// Save aliases to disk
fn save_aliases(aliases: &BTreeMap<String, String>) -> Result<()> {
    let path = ensure_aliases_file()?;
    let content = serde_json::to_string_pretty(aliases)?;
    fs::write(&path, content)?;
    Ok(())
}

/// List all registered aliases
pub fn list() -> Result<()> {
    let aliases = load_aliases()?;

    println!();
    if aliases.is_empty() {
        println!("  {}", color::note("no aliases registered."));
        println!();
        println!("  {}", color::info("usage: uwu alias <name> <command>"));
    } else {
        println!("  {}", color::header("aliases:"));
        for (name, cmd) in &aliases {
            println!(
                "    {} {} {}",
                color::accent(name),
                color::note("->"),
                cmd
            );
        }
    }

    Ok(())
}

/// Show a specific alias
pub fn show(name: &str) -> Result<()> {
    let aliases = load_aliases()?;

    println!();
    match aliases.get(name) {
        Some(cmd) => {
            println!(
                "    {} {} {}",
                color::accent(name),
                color::note("->"),
                cmd
            );
        }
        None => {
            bail!("alias '{}' not found", name);
        }
    }

    Ok(())
}

/// Add or update an alias
pub fn add(name: &str, command: &str) -> Result<()> {
    let mut aliases = load_aliases()?;
    let is_update = aliases.contains_key(name);

    aliases.insert(name.to_string(), command.to_string());
    save_aliases(&aliases)?;

    println!();
    if is_update {
        utils::print_success(&format!("updated: {} -> {}", name, command));
    } else {
        utils::print_success(&format!("added: {} -> {}", name, command));
    }

    if !utils::is_quiet() {
        println!();
        println!(
            "  {}",
            color::note("run 'uwu reload' to apply in current session")
        );
    }

    Ok(())
}

/// Remove an alias
pub fn remove(name: &str) -> Result<()> {
    let mut aliases = load_aliases()?;

    if aliases.remove(name).is_none() {
        bail!("alias '{}' not found", name);
    }

    save_aliases(&aliases)?;

    println!();
    utils::print_success(&format!("removed alias: {}", name));

    if !utils::is_quiet() {
        println!();
        println!(
            "  {}",
            color::note("run 'uwu reload' to apply in current session")
        );
    }

    Ok(())
}

/// Build PowerShell loader script from alias map
fn build_loader_script(aliases: &BTreeMap<String, String>) -> String {
    let mut script = String::new();

    script.push_str("# uwu alias loader - generated by uwu init\n");
    script.push_str("# Do not edit manually, managed by uwu alias\n\n");

    for (name, cmd) in aliases {
        script.push_str(&format!(
            "Remove-Item \"Alias:\\{}\" -Force -ErrorAction SilentlyContinue\n",
            name
        ));

        if cmd.contains(' ') {
            script.push_str(&format!(
                "function global:{} {{ {} @args }}\n",
                name, cmd
            ));
        } else {
            script.push_str(&format!(
                "Set-Alias -Name {} -Value {} -Scope Global -Force\n",
                name, cmd
            ));
        }
    }

    script
}

/// Generate PowerShell script that loads all aliases
pub fn generate_loader_script() -> Result<String> {
    let aliases = load_aliases()?;
    Ok(build_loader_script(&aliases))
}

/// Output the loader script to stdout (for profile sourcing)
pub fn load() -> Result<()> {
    let script = generate_loader_script()?;
    print!("{}", script);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- build_loader_script: empty ---

    #[test]
    fn loader_empty_aliases() {
        let aliases = BTreeMap::new();
        let script = build_loader_script(&aliases);
        assert!(script.contains("# uwu alias loader"));
        assert!(script.contains("Do not edit manually"));
        // ヘッダだけ、エイリアス行なし
        assert!(!script.contains("Set-Alias"));
        assert!(!script.contains("function global:"));
    }

    // --- build_loader_script: single word command ---

    #[test]
    fn loader_single_word_uses_set_alias() {
        let mut aliases = BTreeMap::new();
        aliases.insert("g".to_string(), "git".to_string());
        let script = build_loader_script(&aliases);

        assert!(script.contains("Set-Alias -Name g -Value git -Scope Global -Force"));
        assert!(!script.contains("function global:g"));
    }

    // --- build_loader_script: multi-word command ---

    #[test]
    fn loader_multi_word_uses_function() {
        let mut aliases = BTreeMap::new();
        aliases.insert("gs".to_string(), "git status".to_string());
        let script = build_loader_script(&aliases);

        assert!(script.contains("function global:gs { git status @args }"));
        assert!(!script.contains("Set-Alias -Name gs"));
    }

    // --- build_loader_script: Remove-Item always present ---

    #[test]
    fn loader_removes_conflicting_alias() {
        let mut aliases = BTreeMap::new();
        aliases.insert("ls".to_string(), "eza".to_string());
        let script = build_loader_script(&aliases);

        assert!(script.contains(
            "Remove-Item \"Alias:\\ls\" -Force -ErrorAction SilentlyContinue"
        ));
    }

    // --- build_loader_script: multiple aliases ---

    #[test]
    fn loader_multiple_aliases_sorted() {
        let mut aliases = BTreeMap::new();
        aliases.insert("z".to_string(), "zoxide".to_string());
        aliases.insert("a".to_string(), "aria2c".to_string());
        aliases.insert("gs".to_string(), "git status".to_string());
        let script = build_loader_script(&aliases);

        // BTreeMap はキーでソートされる => a, gs, z の順
        let pos_a = script.find("Set-Alias -Name a").unwrap();
        let pos_gs = script.find("function global:gs").unwrap();
        let pos_z = script.find("Set-Alias -Name z").unwrap();
        assert!(pos_a < pos_gs);
        assert!(pos_gs < pos_z);
    }

    // --- build_loader_script: mixed types ---

    #[test]
    fn loader_mixed_single_and_multi() {
        let mut aliases = BTreeMap::new();
        aliases.insert("g".to_string(), "git".to_string());
        aliases.insert("gp".to_string(), "git push".to_string());
        let script = build_loader_script(&aliases);

        assert!(script.contains("Set-Alias -Name g -Value git"));
        assert!(script.contains("function global:gp { git push @args }"));
    }

    // --- build_loader_script: special characters ---

    #[test]
    fn loader_command_with_flags() {
        let mut aliases = BTreeMap::new();
        aliases.insert("ll".to_string(), "eza -la --icons".to_string());
        let script = build_loader_script(&aliases);

        assert!(script.contains("function global:ll { eza -la --icons @args }"));
    }

    // --- build_loader_script: header ---

    #[test]
    fn loader_header_format() {
        let aliases = BTreeMap::new();
        let script = build_loader_script(&aliases);
        let lines: Vec<&str> = script.lines().collect();
        assert_eq!(lines[0], "# uwu alias loader - generated by uwu init");
        assert_eq!(lines[1], "# Do not edit manually, managed by uwu alias");
        assert_eq!(lines[2], ""); // 空行
    }

    // --- build_loader_script: each alias gets remove + set ---

    #[test]
    fn loader_each_alias_has_remove_then_set() {
        let mut aliases = BTreeMap::new();
        aliases.insert("cat".to_string(), "bat".to_string());
        let script = build_loader_script(&aliases);

        let remove_pos = script.find("Remove-Item \"Alias:\\cat\"").unwrap();
        let set_pos = script.find("Set-Alias -Name cat").unwrap();
        assert!(remove_pos < set_pos);
    }

    // --- aliases_file ---

    #[test]
    fn aliases_file_path_structure() {
        let path = aliases_file();
        assert_eq!(path.file_name().unwrap(), "aliases.json");
        assert_eq!(path.parent().unwrap().file_name().unwrap(), ".uwu");
    }
}
